### ISSUE TITLE
Do you have any plan to add suffix for path?

### ISSUE THREAD

**Issue by hykw** [onkel-dirtus/logger_file_backend#12]
In this case, the log file is logs/info.log.

```elixir
config :logger, :foo,
  path: "logs/info.log",
  level: :info,
```

It's useful that the log file would be `logs/info.log.20160105123456`, isn't it?

```elixir
config :logger, :foo,
  path: "logs/info.log.",
  level: :info,

  suffix: some_function_which_returns_datetime()
```

**Comment by onkel-dirtus** [comment]
Would this work for you?

```elixir
config :logger, :foo,
  path: "logs/info.log.#{some_function_which_returns_datetime()}",
  level: :info
```

**Comment by hykw** [comment]
Is the path value evaluated each access?

I've tested the code below, but the suffix is fixed with the value when the worker launched by Supervisor in lib/xxxx.ex

```elixir
path: "logs/phoenix.log.#{List.last(Tuple.to_list(:os.timestamp()))}",   
```

**Comment by onkel-dirtus** [comment]
Well, back to your original question. I don't see the value in adding a suffix. Can you explain why you thing it would be useful?

**Comment by hykw** [comment]
In that case, one doesn't need to rotate the log.

**Comment by onkel-dirtus** [comment]
I don't think `suffix` support, alone, is going to be enough to provide log rotation. And because one should be able to use `Logger.configure_backend/2` to change the path at runtime, I don't see any need to the feature. Thanks for your interest. I'm going to close this issue, but feel free to continue the conversation if you have more to add.

**Comment by onkel-dirtus** [comment]
@hykw jsvisa/logger_file_backend@6a8731691b may be of interest to you.

**Comment by hykw** [comment]
@onkel-dirtus Thank you for pointing! I'll check and test it now.
