### ISSUE TITLE
Version check for elixir states <= 1.2.0

### ISSUE THREAD

**Issue by redvers** [onkel-dirtus/logger_file_backend#14]
We're at 1.2.1 now.

I originally forked it with a view to submitting a pull request but then I wasn't entirely sure how you wanted to treat the 1.1.0 series.  Wanted to make sure I knew your intent before pulling.

**Comment by midas** [comment]
Any update on this issue?  I am having an issue with this also.

**Comment by onkel-dirtus** [comment]
Sorry about this everyone. I merged a pr that fixed this but neglected to push a new version to hex.pm. This should be resolved in 0.0.7 (just created).
