### ISSUE TITLE
Suspect LoggerFileBackend crashed Phoenix application

### ISSUE THREAD

**Issue by bvjebin** [onkel-dirtus/logger_file_backend#16]
Can you please take a look at this issue and confirm if Logger has anything to do with it? My prod application was crashed yesterday and I have attached the logs with the below given issue. I am using version 0.0.4 of LoggerFileBackend.

**https://github.com/phoenixframework/phoenix/issues/1681**

Note: I had disabled debug mode in prod. I suspect, somehow, the debug mode is enabled and it tried to write some unicode char into file and that failed. Again I couldn't reproduce or confirm that.

Given below is my prod log configuration from prod.exs file:

```
backends = [{LoggerFileBackend, :info}, {LoggerFileBackend, :warn}, {LoggerFileBackend, :error}]
# backends = [{LoggerFileBackend, :debug}, {LoggerFileBackend, :warn}, {LoggerFileBackend, :error}, :console]
config :logger, format: "[$date] [$time] [$level] $metadata $message\n", metadata: [:module, :line], backends: backends

config :logger, :info,
  path: "log/prod.log",
  level: :info,
  format: "[$date] [$time] [$level] $metadata $message\n",
  metadata: [:date, :module, :line]

# config :logger, :debug, path: "log/prod.log", level: :debug

config :logger, :warn,
  path: "log/prod.log",
  level: :warn,
  format: "[$date] [$time] [$level] $metadata $message\n",
  metadata: [:date, :module, :line]

config :logger, :error,
  path: "log/prod.log",
  level: :error,
  format: "[$date] [$time] [$level] $metadata $message\n",
  metadata: [:date, :module, :line]

config :logger, :error,
  path: "log/error.log",
  level: :error,
  format: "[$date] [$time] [$level] $metadata $message\n",
  metadata: [:date, :module, :line]
```

**Comment by bvjebin** [comment]
Adding @josevalim in the loop.

**Comment by josevalim** [comment]
Hi @onkel-dirtus!

I am not sure how the file backend works but Logger receives chardata. This means that:

1. If you don't open up the file as utf8, you will need to call the unicode functions before writing down. If you do so, beware that translation may fail, and you will need to act accordingly.

2. If you open up the file as utf8, writing to it may fail with invalid data, then you need to act accordingly too.

Here is how we solved it for the console backend: https://github.com/elixir-lang/elixir/commit/94a5744c106f1cb0b064b251d8c3f2b83d77093a

You will likely have to port the prune function to this project until you can depend on something like Elixir v1.3.

**Comment by onkel-dirtus** [comment]
@josevalim Thanks for the link. Very helpful, as always.
@bvjebin Thank you for using the project and reporting the issue. My apologies for not getting to it sooner. I've included the prune function linked above to this project and released a new version that appears to resolve the issue. I hope you'll be able to use it in your project. Please let me know if I can be of any further help.

**Comment by bvjebin** [comment]
@onkel-dirtus Thank you very much. 
I see your changes in master branch. Should I use master or will you create a new tag?

**Comment by onkel-dirtus** [comment]
@bvjebin Rats! I forgot to push the branch, but v0.0.8 should be available via hex.
