### ISSUE TITLE
0.0.10

### ISSUE THREAD

**Issue by alex88** [onkel-dirtus/logger_file_backend#27]
I've seen the repo has a fix and the version has been bumped to 0.0.10 however it's not on hex.pm, did you forgot to push it or there is a reason?

**Comment by noggenfogger86** [comment]
version 0.0.10 was my mistake.
see my branch.
https://github.com/noggenfogger86/logger_file_backend

**Comment by Mazyod** [comment]
I think a version bump would be good anywho :3

**Comment by leifg** [comment]
Yeah would be great to have a new version

**Comment by onkel-dirtus** [comment]
done...finally.
