### ISSUE TITLE
Please adapt it to new Elixir Version(1.5.1) PLS!

### ISSUE THREAD

**Issue by neroishero** [onkel-dirtus/logger_file_backend#42]
GenEvent is depracated in Elixir v1.5.1, pls adapt to the new version, thanks.

**Comment by areski** [comment]
@onkel-dirtus merged the PR -> https://github.com/onkel-dirtus/logger_file_backend/pull/43
You might want to close this issue.

**Comment by onkel-dirtus** [comment]
@areski Thx

**Comment by wrachwal** [comment]
@onkel-dirtus Work under commit dd2f40d is not enough. I get tons of warnings like
```
12:57:34.611 [warn]  ** Undefined handle_info in LoggerFileBackend
** Unhandled message: {:io_reply, #Reference<0.1509840159.3980918785.102111>, :ok}
```
Please check what callback functions erlang's gen_event requires to be defined explicitly.

**Comment by johnc219** [comment]
I am also getting the behavior described by @wrachwal
