### ISSUE TITLE
Support elixir 1.6 logger 

### ISSUE THREAD

**Issue by alirajabi** [onkel-dirtus/logger_file_backend#48]
Elixir logger had an issue on heavy load
So Elixir added some new features in new version  like `sync_threshold` and `discard_threshold` to improve performance.

Please add these features

**Comment by HugoLnx** [comment]
Hi, @alirajabi !
These options does not depend on Backend implementation.
On sync mode Logger will use `:gen_event.sync_notify`, but on async_mode it will use `:gen_event.notify`. As you can see on [logger.ex#L780](https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L780).

And when Logger is on discard mode it will only stop notifying the backend, as you can see on [logger.ex#L615](https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L615)

**Comment by alirajabi** [comment]
Thanks for answer
