### ISSUE TITLE
GenEvent module is deprecated

### ISSUE THREAD

**Issue by ourway** [onkel-dirtus/logger_file_backend#53]
warning: the GenEvent module is deprecated, see its documentation for alternatives
  lib/logger_file_backend.ex:5

**Comment by evnu** [comment]
This should have be fixed with https://github.com/onkel-dirtus/logger_file_backend/commit/dd2f40d4f68c8d306033412b9cef29bbc676baee, but is not yet released on hex.pm.

**Comment by onkel-dirtus** [comment]
released with [v0.0.11](https://hex.pm/packages/logger_file_backend/0.0.11)
