### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by axelson** [onkel-dirtus/logger_file_backend#59]
Is it possible to get a new release that includes https://github.com/onkel-dirtus/logger_file_backend/pull/43 ?

**Comment by PragTob** [comment]
:wave: bump? @onkel-dirtus

**Comment by mstratman** [comment]
I'm happy to put together a release if that helps and you're willing to grant access: `mix hex.owner add 
logger_file_backend mstratman`

On a related note, here's a CHANGELOG that can ship with the next release: https://github.com/onkel-dirtus/logger_file_backend/pull/64

**Comment by MeerKatDev** [comment]
Was the project abandoned?

**Comment by mstratman** [comment]
Ping @onkel-dirtus  :)

**Comment by onkel-dirtus** [comment]
@MeerKatDev No, not abandoned. Just neglected 😉 Give me a minute to wrap my head around the state of things and I'll get a release out tonight. Pinky promise.

**Comment by PragTob** [comment]
thank you @onkel-dirtus !
