### ISSUE TITLE
Logger crash

### ISSUE THREAD

**Issue by fremontmj** [onkel-dirtus/logger_file_backend#6]
This crashes the Logger:

Logger.debug(" “ ")
(That's a curly quote in there)

>>>> 20:31:58.104 [error] --> GenEvent handler {LoggerFileBackend, :file_log} installed at Logger
** (exit) an exception was raised:
    ** (ErlangError) erlang error: :no_translation
        (stdlib) :io.put_chars(#PID<0.170.0>, :unicode, [">>>> ", ["20", 58, "31", 58, "58", 46, [48, "94"]], " [", "debug", "] --> ", "“", "\n"])
        lib/logger_file_backend.ex:55: LoggerFileBackend.log_event/5
        (elixir) lib/gen_event.ex:990: GenEvent.do_handler/3
        (elixir) lib/gen_event.ex:831: GenEvent.server_update/5
        (elixir) lib/gen_event.ex:816: GenEvent.server_notify/7
        (elixir) lib/gen_event.ex:789: GenEvent.server_event/4
        (elixir) lib/gen_event.ex:578: GenEvent.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

Here's my config.exs:
    config :logger, :console,
      level: :debug,
      format: ">>>> $time [$level] --> $message\n"

      config :logger,
        backends: [{LoggerFileBackend, :file_log}, :console]

      config :logger, :file_log,
        path: "/var/log/riffer4/file_log",
       level: :debug,
      format: ">>>> $time [$level] --> $message\n"

Regards,

Mike

**Comment by onkel-dirtus** [comment]
That's a pity. I'll take a look. Thanks!

**Comment by bongole** [comment]
Maybe this is old version problem.
Latest logger_file_backend version on hex.pm is 0.0.3 that is not utf8 aware.
https://hex.pm/packages/logger_file_backend

Please release utf8 aware new version.

**Comment by onkel-dirtus** [comment]
Thanks @bongole Version 0.0.4 has been published
