### ISSUE TITLE
Several warnings with Elixir 1.7.4

### ISSUE THREAD

**Issue by shifters67** [onkel-dirtus/logger_file_backend#60]
Hi

the following warnings are generated by the compiler with the above elixir version

warning: the GenEvent module is deprecated, see its documentation for alternatives
  lib/logger_file_backend.ex:5

warning: GenEvent.__using__/1 is deprecated. Use one of the alternatives described in the documentation for the GenEvent module
  lib/logger_file_backend.ex:5

**Comment by OvermindDL1** [comment]
Still getting the warnings with the latest published version on Elixir 1.8.0.

**Comment by rodrigues** [comment]
It was already merged in master: https://github.com/onkel-dirtus/logger_file_backend/pull/43

We just don't have a new release, which is also the subject of this other issue: https://github.com/onkel-dirtus/logger_file_backend/issues/59

**Comment by shifters67** [comment]
Ah, thanks for the update - have switched from hex version to git direct and it compiles fine

Many thanks!

Tom

**Comment by OvermindDL1** [comment]
> Ah, thanks for the update - have switched from hex version to git direct and it compiles fine

Until it's published I'm not sure this should be closed.  I can't use git dependencies at work.  ^.^;
